### ISSUE TITLE
Compatibility issue with Expo SDK 51

### ISSUE THREAD

**Issue by TheoNaulet** [tamagui/starter-free#25]
Current Behavior : 
After upgrading to Expo SDK 51, the project fails to compile with the error `TypeError: Cannot read properties of undefined (reading 'NativeModule')`.

![Capture d’écran 2024-05-14 à 16 27 23](https://github.com/tamagui/tamagui/assets/98829104/5ff22a24-01dc-407e-a097-a6da5544244c)

Expected Behavior : 
The project should compile without errors and work correctly with Expo SDK 51.

Tamagui Version: 
1.98.0

Platform : 
Web

Reproduction :

1. Clone the Tamagui starter from the latest version.
2. Update Expo to version 51.0.0 in the `package.json` file.
3. Run `npm install` or `yarn install` to update dependencies.
4. Start the project with `yarn web`.

OR 

You can clone my test repository to reproduce the issue: [Test Repository](https://github.com/TheoNaulet/testapp.git).

**Comment by jikyu** [comment]
Running into this as well with a ton of expo libraries on web - expo-linking, expo-web-browser, etc.

**Comment by natew** [comment]
Can you try something like this maybe as a workaround, put it in a `patch` file and `import './patch'` as the first import in your app:

```
import * as React from 'react'

React.startTransition = (cb) => cb()
```

**Comment by jikyu** [comment]
I tried creating that file and importing it as the first thing in my next's _app.tsx but that didn't solve thie problem

**Comment by Tekdey** [comment]
I have the same problem. Is there a solution or a fix ?

**Comment by jikyu** [comment]
@TheoNaulet If you have takeout and follow latest guide + make sure package version matches, everything seems to work with Expo 51

**Comment by nnhan0719** [comment]
<img width="888" alt="image" src="https://github.com/user-attachments/assets/1a5efaab-9968-4965-b07d-94556a9d0fa8">

Pls comment line:
`// export default globalThis.expo.NativeModule;`

and 

`// export default globalThis.expo.SharedObject;`
