### ISSUE TITLE
Fail to running on local machine

### ISSUE THREAD

**Issue by ridhoassuryadi** [tamagui/starter-free#31]
**Description**
I got error when to try running in my local machine, when exec "yarn run android" I got the error messages like this:

```
* What went wrong:
Execution failed for task ':expo-modules-core:configureCMakeDebug[arm64-v8a]'.
> [CXX1214] /Users/ridho/go/src/github.com/raizora/starter-free/node_modules/expo-modules-core/android/CMakeLists.txt debug|arm64-v8a : User has minSdkVersion 22 but library was built for 23 [//ReactAndroid/fabricjni]

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.
```

I tried to change `minSdkVersion` to 23 but still got error, how i can solve this one?

**Comment by jonsherrard** [comment]
I would try setting up a seperate Expo project following their setup instructions, and check if that builds. If that works, but the starter expo project doesn't. Let us know.
