### ISSUE TITLE
"You forgot to add 'mini-css-extract-plugin' plugin"

### ISSUE THREAD

**Issue by shashwat2003** [tamagui/starter-free#44]
I am using this starter in my app, after updating to the latest version(v1.112.14)
I am getting this error when trying to run my next app:
```
 ⨯ ../../node_modules/@tamagui/core/reset.css
Error: You forgot to add 'mini-css-extract-plugin' plugin (i.e. `{ plugins: [new MiniCssExtractPlugin()] }`), please read https://github.com/webpack-contrib/mini-css-extract-plugin#getting-started
Import trace for requested module:
../../node_modules/@tamagui/core/reset.css
./app/NextTamaguiProvider.tsx
```
ScreenShot:
<img width="1079" alt="Screenshot 2024-10-02 at 9 43 05 PM" src="https://github.com/user-attachments/assets/adc605e3-8b49-401f-b025-cbce553f9406">

**Comment by NicolasBorlet** [comment]
cd apps/next
yarn add mini-css-extract-plugin
cd ../
yarn
yarn web

work for me

**Comment by elmaystero** [comment]
@NicolasBorlet tried your solution still getting same error. any suggestions @natew ? stuck in this issue for now.

**Comment by elmaystero** [comment]
I faced same issue and what worked for me is to remove "mini-css-extract-plugin" from /apps/next/package.json
then go to root folder and run yarn. and you're good to go.

**Comment by jonsherrard** [comment]
Ah ok I thought I'd fixed this by _adding_ mini-css-extract-plugin as per @NicolasBorlet's fix.

So @elmaystero saying you need to remove it is perplexing. Will take another look at it shortly.

**Comment by shashwat2003** [comment]
I can confirm @NicolasBorlet 's fix is working on my end. I cannot find `mini-css-extract-plugin` in my `package.json` for `apps/next` before adding it as per @elmaystero .

**Comment by jonsherrard** [comment]
@shashwat2003 that makes sense, I only added mini-css-extract-plugin a few hours ago - so maybe Elmaystero installed starter-free since then.

**Comment by elmaystero** [comment]
sorry guys, today I'm getting same error again. even created new starter-free project to make sure I'm using latest version. adding or removing mini-css-extract-plugin from nextjs project doesn't resolve the error:

 ⨯ ../../node_modules/@tamagui/core/reset.css
Error: You forgot to add 'mini-css-extract-plugin' plugin (i.e. `{ plugins: [new MiniCssExtractPlugin()] }`), please read https://github.com/webpack-contrib/mini-css-extract-plugin#getting-started
Import trace for requested module:
../../node_modules/@tamagui/core/reset.css
./app/NextTamaguiProvider.tsx
 GET / 500 in 36748ms
 GET / 500 in 115ms

@jonsherrard @shashwat2003 @natew

**Comment by shashwat2003** [comment]
@elmaystero Same here, it is a recurring issue for me, it randomly appears and then disappears, once I remove the package(mini-css-extract-plugin) and then reinstall it, and then run the server. Don't know if it is a next js issue or tamagui. I am thinking of migrating to OneStack, but it's in beta.

**Comment by elmaystero** [comment]
@shashwat2003 yes it randomly happens. I invested couple of hours investigating the issue and the worked solution for me is changing the css support with custom configuration in nextjs, here's the steps:

 1- remove mini-css-extract-plugin from apps/next/package.json
 2- run "yarn add css-loader style-loader --dev" inside apps/next folder
 3- replace apps/next/next.config.js file with this code:
 
 `/** @type {import('next').NextConfig} */
const { withTamagui } = require('@tamagui/next-plugin')
const { join } = require('node:path')

const boolVals = {
  true: true,
  false: false,
}

const disableExtraction =
  boolVals[process.env.DISABLE_EXTRACTION] ?? process.env.NODE_ENV === 'development'

const plugins = [
  withTamagui({
    config: '../../packages/config/src/tamagui.config.ts',
    components: ['tamagui', '@my/ui'],
    appDir: true,
    importsWhitelist: ['constants.js', 'colors.js'],
    outputCSS: process.env.NODE_ENV === 'production' ? './public/tamagui.css' : null,
    logTimings: true,
    disableExtraction,
    shouldExtract: (path) => {
      if (path.includes(join('packages', 'app'))) {
        return true
      }
    },
    excludeReactNativeWebExports: ['Switch', 'ProgressBar', 'Picker', 'CheckBox', 'Touchable'],
  }),
]

module.exports = () => {
  /** @type {import('next').NextConfig} */
  let config = {
    typescript: {
      ignoreBuildErrors: true,
    },
    modularizeImports: {
      '@tamagui/lucide-icons': {
        transform: `@tamagui/lucide-icons/dist/esm/icons/{{kebabCase member}}`,
        skipDefaultConversion: true,
      },
    },
    transpilePackages: [
      'solito',
      'react-native-web',
      'expo-linking',
      'expo-constants',
      'expo-modules-core',
    ],
    experimental: {
      scrollRestoration: true,
    },
    webpack: (config, { isServer }) => {
      config.module.rules.push({
        test: /\.css$/i,
        use: ['style-loader', 'css-loader'],
        sideEffects: true,
      })

      // Handle fonts
      config.module.rules.push({
        test: /\.(woff|woff2|eot|ttf|otf)$/i,
        type: 'asset/resource',
        generator: {
          filename: 'static/fonts/[name].[hash][ext]',
        },
      })

      return config
    },
  }

  for (const plugin of plugins) {
    config = {
      ...config,
      ...plugin(config),
    }
  }

  return config
}
` 
4- delete caching files "apps/next/.next" folder
5- go back to root folder and run yarn then yarn web

if you get any error for font-inter/css/400 or 700 do the following:

 just go to apps\next\app\NextTamaguiProvider.tsx and apps\next\pages\_app.tsx and comment below lines:

// import '@tamagui/font-inter/css/400.css'
// import '@tamagui/font-inter/css/700.css'

let me know if this solution works for you.

**Comment by elmaystero** [comment]
@jonsherrard please re-open the issue as it still happening randomly.

**Comment by maximblack** [comment]
`1.112.6` works nice, something in `1.112.7` breaks it

**Comment by fr0staman** [comment]
`1.112.23` fixes it
I updated my [fork](https://github.com/fr0staman/tamagui-react-native-i18next-zustand-starter) `1.112.22` -> `1.112.23` and the error disappeared

**Comment by elmaystero** [comment]
yes @maximblack 1.112.6 is working just fine. something is breaking since 1.112.7 version. FYI @jonsherrard
